version: '3.8'

services:
  forum-linux:
    build: .
    container_name: trabalho03-linux
    ports:
      - "8080:80"
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./evidencias:/app/evidencias
    stdin_open: true
    tty: true